pipeline {
  agent any

  environment {
    IMAGE_NAME    = "myapp"            // image name
    APP_HOST_DEV  = "myapp-dev.local"  // ingress host for dev
    NAMESPACE_DEV = "dev"
    RELEASE_DEV   = "myapp-dev"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Image (local)') {
      steps {
        script {
          def tag = "build-${env.BUILD_NUMBER}"
          env.IMAGE_TAG = tag

          sh """
            docker build -f docker/Dockerfile -t ${IMAGE_NAME}:${tag} .
          """
        }
      }
    }

    stage('Helm Upgrade (dev)') {
      steps {
        script {
          sh """
            helm upgrade --install ${RELEASE_DEV} k8s/helm \
              --namespace ${NAMESPACE_DEV} \
              --create-namespace \
              -f k8s/helm/values-dev.yaml \
              --set image.repository=${IMAGE_NAME} \
              --set image.tag=${IMAGE_TAG}
          """
        }
      }
    }

    stage('Wait for Rollout') {
      steps {
        script {
          sh """
            kubectl rollout status deployment/myapp-dev-helm \
              -n dev \
              --timeout=300s || kubectl -n dev get pods && kubectl -n dev describe deployment/myapp-dev-helm
          """
        }
      }
    }

    stage('Smoke Test via Ingress') {
      steps {
        script {
          sh """
             kubectl -n dev port-forward svc/myapp-dev-helm 8080:80 >/tmp/pf.log 2>&1 &
        PF_PID=$!
        sleep 5

        # Health check
        curl -fsS http://127.0.0.1:8080/ || { echo "Health check failed"; kill $PF_PID; exit 1; }

        # Cleanup
        kill $PF_PID  
          """
        }
      }
    }
  }

  post {
    failure {
      script {
        echo "Deployment or smoke tests FAILED, rolling back dev..."
        sh """
          PREV=\$(helm history ${RELEASE_DEV} -n ${NAMESPACE_DEV} -o json | jq -r '.[-2].revision')
          helm rollback ${RELEASE_DEV} \${PREV} -n ${NAMESPACE_DEV} --wait
        """
      }
    }
  }
}
